tap "hashicorp/tap"
brew "awscli"
brew "azure-cli"
brew "bat"
brew "btop"
brew "fzf"
brew "fd"
brew "git-delta"
brew "python@3.14"
brew "go"
brew "jq"
brew "zoxide"
brew "nmap"
brew "pre-commit"
# brew "pyright"
# brew "ruby@3.2"
brew "ruff"
brew "tlrc"
brew "uv"
brew "telnet"
brew "tree"
brew "harlequin"
brew "atuin"
brew "hashicorp/tap/terraform"
brew "starship"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
cask "bitwarden"
cask "docker-desktop"
cask "iina"
# cask "qbittorrent"
cask "monitorcontrol"
cask "ghostty"
cask "codex"
# cask "zen"
cask "zed"
cask "plex-media-server"
cask "tailscale-app"
cask "font-geist-mono"
cask "arc"
